name: Lint Python Code Blocks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Python Code Blocks in Markdown
        uses: alasdairwilson/run-py-markdown@main
        with:
          directory: .
